import pytest

from medguard_core.config import MedGuardConfig
from medguard_core.proxy import create_app


pytestmark = pytest.mark.asyncio


async def test_dashboard_guides_a_first_time_user(aiohttp_client):
    client = await aiohttp_client(create_app(MedGuardConfig()))
    html = await (await client.get("/dashboard")).text()

    for text in (
        "Check a clinical AI request before it is sent",
        "What should the AI do?",
        "Patient record or retrieved content (optional)",
        "Check safety only",
        "Use a sample AI response",
        "Use a connected AI model",
        "Use demonstration data only",
    ):
        assert text in html

    assert 'aria-describedby="userInputHelp userInputError"' in html
    assert 'aria-describedby="ragInputHelp"' in html


async def test_dashboard_uses_plain_language_outcomes(aiohttp_client):
    client = await aiohttp_client(create_app(MedGuardConfig()))
    html = await (await client.get("/dashboard")).text()

    assert "Safe to continue" in html
    assert "Review recommended" in html
    assert "Request stopped" in html
    assert "Technical details" in html
    assert "function friendlyOutcome(decision, riskAction)" in html


async def test_dashboard_explains_protection_controls(aiohttp_client):
    client = await aiohttp_client(create_app(MedGuardConfig()))
    html = await (await client.get("/dashboard")).text()

    assert "Detect unsafe instructions" in html
    assert "Separate patient data from instructions" in html
    assert "Detect hidden information leaks" in html
    assert "Stop unsafe requests" in html
    assert "Remove unsafe instructions and continue" in html


async def test_dashboard_keeps_internal_details_out_of_primary_copy(aiohttp_client):
    client = await aiohttp_client(create_app(MedGuardConfig()))
    html = await (await client.get("/dashboard")).text()

    assert "Processed messages will appear" not in html
    assert "raw JSON" not in html
    assert "generated by" not in html.lower()
